version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.3
    steps:
      - checkout
      - add_ssh_keys
      - run: git tag -l
      - run: mkdir -p ./artifacts
      - run: cp ./semver_version.sh ./artifacts/./semver_version.sh
      - run: ./semver_version.sh -l text -f ./artifacts/version.txt -o none
      - persist_to_workspace:
            root: ./artifacts
            paths:
            - .
  release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - add_ssh_keys
      - attach_workspace:
          at: ./artifacts
      - run: ./artifacts/semver_version.sh -l text -f ./artifacts/version.txt
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./artifacts/version.txt)
            rm ./artifacts/version.txt
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  main:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
